### ISSUE TITLE
Analyze crashes on trying to create app’s presenter

### ISSUE THREAD

**Issue by jtojnar** [TomasVotruba/barista#3]
Running `vendor/bin/barista analyze` in my Nette project using 08fa2df crashes with the following error:

```
Fatal error: Uncaught Nette\DI\ServiceCreationException: Service 'application.1' (type of App\Presenters\DashboardPresenter): Service of type App\Model\HelperLoader required by $helperLoader in App\Presenters\BasePresenter::__construct() not found. Did you add it to configuration file? in /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php:650
Stack trace:
#0 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php(577): Nette\DI\Resolver::autowireArgument(Object(ReflectionParameter), Object(Closure))
#1 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php(232): Nette\DI\Resolver::autowireArguments(Object(ReflectionMethod), Array, Object(Closure))
#2 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php(226): Nette\DI\Resolver->completeStatement(Object(Nette\DI\Definitions\Statement))
#3 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php(168): Nette\DI\Definitions\ServiceDefinition->complete(Object(Nette\DI\Resolver))
#4 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerBuilder.php(332): Nette\DI\Resolver->completeDefinition(Object(Nette\DI\Definitions\ServiceDefinition))
#5 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Compiler.php(275): Nette\DI\ContainerBuilder->complete()
#6 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Compiler.php(212): Nette\DI\Compiler->processBeforeCompile()
#7 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\DI\Compiler->compile()
#8 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerLoader.php(81): Nette\DI\ContainerLoader->generate('Container_55cc0...', Array)
#9 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile('Container_55cc0...', Array)
#10 /home/jtojnar/Projects/eudyptes/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(274): Nette\DI\ContainerLoader->load(Array, Array)
#11 /home/jtojnar/Projects/eudyptes/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(252): Nette\Bootstrap\Configurator->loadContainer()
#12 /home/jtojnar/Projects/eudyptes/vendor/barista/barista/src/DI/BaristaContainerFactory.php(32): Nette\Bootstrap\Configurator->createContainer()
#13 /home/jtojnar/Projects/eudyptes/vendor/barista/barista/bin/barista.php(31): Barista\DI\BaristaContainerFactory->create(Array)
#14 /home/jtojnar/Projects/eudyptes/vendor/barista/barista/bin/barista(4): require('/home/jtojnar/P...')
#15 /home/jtojnar/Projects/eudyptes/vendor/bin/barista(117): include('/home/jtojnar/P...')
#16 {main}
  thrown in /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php on line 650
```

Initially reported in #2.

**Comment by TomasVotruba** [comment]
I think the search config is hooking to your project and tries to load your appDir parameter.

How does it change, when you register services manually in barista config?

**Comment by TomasVotruba** [comment]
I think the search config is hooking to your project and tries to load your appDir parameter.

How does it change, when you register services manually in barista config?

**Comment by jtojnar** [comment]
It is the same error when I drop the `search` extension in favour of manually registered services. I will try to reproduce this with nette-sandbox.

**Comment by jtojnar** [comment]
I actually got a [different error](https://github.com/TomasVotruba/barista/issues/4). I saw that one before as well.

**Comment by jtojnar** [comment]
Something fishy is in place. I deleted the presenters and run `composer dump-autoload` and now it cannot find the command. Maybe something with how `symfony/console` finds commands.

```
$ vendor/bin/barista analyze
                                     
  Command "analyze" is not defined.
```

**Comment by jtojnar** [comment]
```ShellSession
$ vendor/bin/barista list
[...]
Available commands:
  completion  Dump the shell completion script
  help        Display help for a command
  lint        Lint your Latte files with your own Latte\Engine. Provide it via "barista.neon" > "parameters" > "latteProviderFile" parameter
  list        List commands
```

/me pulling hair

**Comment by TomasVotruba** [comment]
I'd be really interested in reproducer for this original one :) 

```bash
Uncaught Nette\DI\ServiceCreationException: Service 'application.1' (t
```

**Comment by jtojnar** [comment]
Right. Since trying it in nette sandbox just gave me a different error message, I am trying to simplify my project by deleting files left and right. Only to get more and more bizarre errors.

I should probably step away from PHP for today.

**Comment by TomasVotruba** [comment]
Yea, take your time and relax. Debugging can suck out of live very quickly, keep healthy :beer: :relaxed:

**Comment by TomasVotruba** [comment]
I tried to add more own dependency services, but it did not help to crash :/

The search extension works really poorly. I wish it allowed PHP syntax so we can use normal absolute path.

This is my random guess:
https://github.com/TomasVotruba/barista/commit/a0455c33805ea01896992b00819d1c82b95f2516

**Comment by jtojnar** [comment]
As mentioned, it does happen when I remove the `search` block so unless Nette adds it implicitly somehow, that should not be it. I ate something so hopefully I will be more productive now.

Edit: Right, still the same at a0455c3.

**Comment by jtojnar** [comment]
After trying almost every possible subset of files to delete from the project, it turned out that `classmap` autoload is the determining factor, see https://github.com/jtojnar/repro/tree/f0d5ae9cc3a8e68b3d7098b172a5db80dcea0f2d/barista-3.

I have decided to port the legacy app to PSR-4 (unfortunately, [Rector\PSR4\Rector\FileWithoutNamespace\NormalizeNamespaceByPSR4ComposerAutoloadRector](https://github.com/rectorphp/rector/blob/main/rules/PSR4/Rector/FileWithoutNamespace/NormalizeNamespaceByPSR4ComposerAutoloadRector.php) is insufficient).

Not sure if this is worth debugging further.
